# Generated by Django 5.1.2 on 2024-10-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_district_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='icon',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
    ]
