# Generated by Django 5.1.2 on 2024-10-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_remove_district_icon_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='ad_photos/'),
        ),
    ]
