# Generated by Django 5.1.2 on 2024-10-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_ad_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_photo/'),
        ),
    ]
