# Generated by Django 5.1.2 on 2024-10-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_seller_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
